### ISSUE TITLE
iou loss

### ISSUE THREAD

**Issue by WillLiGitHub** [OlgaChernytska/2D-Hand-Pose-Estimation-RGB#1]
iou loss return negative float value, some wrong?

**Comment by OlgaChernytska** [comment]
Hi, 
Sorry, I don't really understand your question.
Are you running the code from this repo without any changes and getting negative IoU loss?
Or are you writing your own code or adding some modifications to mine?

In general, yes, IoU loss can't be negative by definition. I recommend you to check whether values in your heatmaps (Y) are positive and values in model predictions (Y pred) are also positive.
